#!/bin/bash

# grep -H . /sys/class/drm/card*-*/status | grep :connected

# This file would be sourced by gamescope-session script (meant for
# ChimeraOS devices).
export LANG=en_US.UTF-8
SYS_ID="$(cat /sys/devices/virtual/dmi/id/product_name)"
CPU_VENDOR=$(cat /proc/cpuinfo | grep vendor_id | head -n 1 | cut -d : -f 2 | xargs)
CPU_MODEL=$(cat /proc/cpuinfo | grep "model name" | head -n 1 | cut -d : -f 2 | xargs)

# OXP 60Hz Devices
OXP_LIST="ONE XPLAYER:ONEXPLAYER 1 T08:ONEXPLAYER 1S A08:ONEXPLAYER 1S T08:ONEXPLAYER mini A07:ONEXPLAYER mini GA72:ONEXPLAYER mini GT72:ONEXPLAYER Mini Pro:ONEXPLAYER GUNDAM GA72:ONEXPLAYER 2 ARP23:ONEXPLAYER 2 PRO ARP23P:ONEXPLAYER 2 PRO ARP23P EVA-01"
AOK_LIST="AOKZOE A1 AR07:AOKZOE A1 Pro:AOKZOE A2 Pro"
if [[ ":$OXP_LIST:" =~ ":$SYS_ID:" ]] || [[ ":$AOK_LIST:" =~ ":$SYS_ID:" ]]; then
  if [[ "$CPU_VENDOR" =~ "GenuineIntel" ]]; then
    OUTPUT_CONNECTOR='*,DSI-1'
  else
    OUTPUT_CONNECTOR='*,eDP-1'
  fi
  
  ORIENTATION=left
  CUSTOM_REFRESH_RATES="40-60"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,60
fi

# OXP 120hz Devices
OXP_120_LIST="ONEXPLAYER F1:ONEXPLAYER F1 EVA-01"
if [[ ":$OXP_120_LIST:" =~ ":$SYS_ID:" ]]; then
  DRM_MODE=custom
  DRM_MODE_CUSTOM_DIR=/usr/share/gamescope-session-plus/modelines
  ORIENTATION=left

  export STEAM_DISPLAY_REFRESH_LIMITS=40,120
fi

# AYANEO AIR Devices
AIR_LIST="AIR:AIR Pro:AIR 1S:AIR 1S Limited"
if [[ ":$AIR_LIST:" =~ ":$SYS_ID:" ]]; then
  ORIENTATION=left
  CUSTOM_REFRESH_RATES="50-60"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,60
fi

# AYANEO FLIP Devices
FLIP_LIST="FLIP KB:FLIP DS"
if [[ ":$FLIP_LIST:" =~ ":$SYS_ID:" ]]; then
  ORIENTATION=left
  CUSTOM_REFRESH_RATES="60,80,90,100,110,120"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,120
fi

# AYANEO Plus
AIR_PLUS_LIST="AIR Plus:SLIDE"
if [[ ":$AIR_PLUS_LIST:" =~ ":$SYS_ID:" ]]; then
  ORIENTATION=left
  CUSTOM_REFRESH_RATES="40-60"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,60
fi

# AYN Loki Devices
AYN_LIST="Loki Max:Loki Zero:Loki MiniPro"
if [[ ":$AYN_LIST:" =~ ":$SYS_ID:" ]]; then
  ORIENTATION=left
  CUSTOM_REFRESH_RATES="40-60"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,60
fi

# GDP Win devices
GDP_LIST="G1619-01:G1621-02:MicroPC:WIN2"
if [[ ":$GDP_LIST:" =~ ":$SYS_ID:" ]]; then
  OUTPUT_CONNECTOR='*,DSI-1'
  ORIENTATION=right
fi

# GPD Win 3
if [[ ":G1618-03:" =~ ":$SYS_ID:" ]]; then
  OUTPUT_CONNECTOR='*,DSI-1'
  ORIENTATION=right
fi

#GPD Win 4 supports 40-60hz refresh rate changing
if [[ ":G1618-04:" =~ ":$SYS_ID:" ]]; then
  ORIENTATION=normal
  CUSTOM_REFRESH_RATES="40-60"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,60
fi

# GPD Win mini
if [[ ":G1617-01:" =~ ":$SYS_ID:" ]]; then
  model_name=$(cat /sys/class/drm/card1-eDP-1/edid | parse-edid 2>/dev/null | grep "ModelName" | cut -d \" -f 2)
  echo "Model Name: $model_name" | systemd-cat -t gamescope-session

  if [[ "$model_name" == "TL070FVXS01-0" ]]; then
    ADAPTIVE_SYNC=1
    ORIENTATION=normal
    CUSTOM_REFRESH_RATES="60,70,80,90,100,110,120"
  else
    # model_name is "MINI"
    ORIENTATION=right
    DRM_MODE=custom
    DRM_MODE_CUSTOM_DIR=/usr/share/gamescope-session-plus/modelines

  fi

  # Pointer options
  TAP_TO_CLICK=1
  TAP_TO_DRAG=1
  TAP_DRAG_LOCK=1
  NATURAL_SCROLL=touchpad

  export STEAM_DISPLAY_REFRESH_LIMITS=40,120

fi

# GPD Win Max2
if [[ ":G1619-04:" =~ ":$SYS_ID:" ]]; then
  ORIENTATION=normal
  CUSTOM_REFRESH_RATES="40-60"

  # Pointer options
  TAP_TO_CLICK=1
  TAP_TO_DRAG=1
  TAP_DRAG_LOCK=1
  NATURAL_SCROLL=touchpad

  export STEAM_DISPLAY_REFRESH_LIMITS=40,60
fi

# Steam Deck
if [[ ":Jupiter:" =~ ":$SYS_ID:" ]]; then
  export STEAM_DISPLAY_REFRESH_LIMITS=40,60
fi

# OLED Steam Deck
if [[ ":Galileo:" =~ ":$SYS_ID:" ]]; then
  export STEAM_DISPLAY_REFRESH_LIMITS=45,90
  export STEAM_GAMESCOPE_FORCE_HDR_DEFAULT=1
  export STEAM_GAMESCOPE_FORCE_OUTPUT_TO_HDR10PQ_DEFAULT=1
fi

# ROG Ally
ALLY_LIST="ROG Ally RC71L_RC71L:ROG Ally RC71L"
if [[ ":$ALLY_LIST:" =~ ":$SYS_ID:" ]]; then
  ADAPTIVE_SYNC=1
  ORIENTATION=normal
  CUSTOM_REFRESH_RATES="60,70,80,90,100,110,120"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,120
fi

# Lenovo Legion Go
if [[ ":83E1:" =~ ":$SYS_ID:" ]]; then
  ADAPTIVE_SYNC=1
  ORIENTATION=left
  CUSTOM_REFRESH_RATES="60,144"

  export STEAM_DISPLAY_REFRESH_LIMITS=60,144
fi

# Minisforum V3
if [[ ":V3:" =~ ":$SYS_ID:" ]]; then
  CUSTOM_REFRESH_RATES="60,90,100,120,144,165"

  export STEAM_DISPLAY_REFRESH_LIMITS=40,165

  # Pointer options
  TAP_TO_CLICK=1
  TAP_TO_DRAG=1
  TAP_DRAG_LOCK=1
  NATURAL_SCROLL=touchpad
fi
